# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n\x0bPlayerState\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcharacter\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\x12\r\n\x05\x66rame\x18\x06 \x01(\x05\x12\x0e\n\x06health\x18\x07 \x01(\x05\x12\x13\n\x0bsuper_gauge\x18\x08 \x01(\x05\"v\n\tGameState\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\r\n\x05timer\x18\x02 \x01(\x05\x12\"\n\x07players\x18\x03 \x03(\x0b\x32\x11.game.PlayerState\x12\x16\n\twinner_id\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\x0c\n\n_winner_id\"L\n\x10GameStateRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x12\n\nplayer1_id\x18\x02 \x01(\x05\x12\x12\n\nplayer2_id\x18\x03 \x01(\x05\"\x95\x01\n\x0bPlayerInput\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12/\n\nkey_action\x18\x02 \x01(\x0e\x32\x1b.game.PlayerInput.KeyAction\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x10\n\x08match_id\x18\x04 \x01(\t\"#\n\tKeyAction\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x32K\n\x0bGameService\x12<\n\x0fStreamGameState\x12\x16.game.GameStateRequest\x1a\x0f.game.GameState0\x01\x32S\n\x0f\x43ontrollService\x12@\n\x11StreamPlayerInput\x12\x11.game.PlayerInput\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERSTATE']._serialized_start=50
  _globals['_PLAYERSTATE']._serialized_end=184
  _globals['_GAMESTATE']._serialized_start=186
  _globals['_GAMESTATE']._serialized_end=304
  _globals['_GAMESTATEREQUEST']._serialized_start=306
  _globals['_GAMESTATEREQUEST']._serialized_end=382
  _globals['_PLAYERINPUT']._serialized_start=385
  _globals['_PLAYERINPUT']._serialized_end=534
  _globals['_PLAYERINPUT_KEYACTION']._serialized_start=499
  _globals['_PLAYERINPUT_KEYACTION']._serialized_end=534
  _globals['_GAMESERVICE']._serialized_start=536
  _globals['_GAMESERVICE']._serialized_end=611
  _globals['_CONTROLLSERVICE']._serialized_start=613
  _globals['_CONTROLLSERVICE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
