
import { Character, Move } from './types';

export const CHARACTERS: Character[] = [
    {
        id: 1,
        name: 'Ryu',
        description: 'A wandering martial artist seeking true strength.',
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB30GUUC3ONODlCcAHIbnxfrInjojX0jF7XjgVbuCV4A87Zerv3Vr1TUubrRQBiG1-TVS8SnbhKpTBsLrIMpKDaX74VCJVqreWXZ60Yv81wHP-unuSJ2QgCpBEL-0o7Oa2eDDLui7srmrSxMubHjSCElkRe4OGHrJbVC6kQVKCxS0p8AY4GtNemvLIbK8Q6ej6z2byBu1uu-LwbPJ_ezoG6DIjJM21qXXd_wxbSz46H9te1d2p6udmUt311DbMzF7WOT_T3qu0okmLw",
        profileImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuD9yXyzbh_iDJrGHYF2nmrU__k94ydfPiNhVJ0iuuajAGwj5f9fRGQqcffWQGj79xxC6zkgiCHR1NBog--pQEIokOivzL6y5-uh7JW0Cs9Epgbif3_xHRbyhjBxgGpdfnMGoJCxwT0Z1lzOpj3QAa4wemqyhuWh6t6XB2-OAoj3U7iO3GeQULa_l5CTgmJcAj2JjfJd6AXIlqqvluWY4c6sBhKqcJhyIFu0qEajonw8e2QSdJRFypkeCvEDi4fyvwl0usoRmP3iqCfm",
        vsImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDPeS-kUqd1n8p-YO83df5ZCmJKdn_Cqx27mSwU8rUfWMSk9JKVc4W1tRbOW6bj-A9D2A6t0ZJpnPKIrgbyGmqYdUlTqWVr0vxVi05_VbbShKEzt1P80Uw0JFOOyDLjsJK3ClAPzIbcBwcLqPn57QNcGSvJuEMR1lZJRlIV-d0Vt-CoxCUBqi81B5Y0_trS2NZS1m2Pt3taU-AmMykX-YIqFq9Pl2RjggwGItZolDUZ2E6dGSz1DmVJvC_qKF0dZd2rWj8j_cljk_OG",
        color: 'emphasis-yellow',
    },
    {
        id: 2,
        name: 'Chun-Li',
        description: 'A skilled Interpol officer with lightning-fast kicks.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBeYIYdDnquSstRZPPbr1UYH20RYwDt8RJEtbp9uPqZitGJx9iRgKiOKiM54NrvfVj_pOF9eBOJLArlxS1awMj_QhA6Mp-rVi3e-fYhrmd7XNalq1MB7SDvNongDJQceO8Fv81LGR6Ypeh5Ih6Rx_rGfWOFRANVZuu_Y8-7hjpsSD40KIcJjKjB2CNAKK9udo8Yxmau_dLZ3xLDlkdT2uU2mz-hwGZTj_nWCK_KClEoh1bjiHHp9Qldhud1OVbeXy5H3BA2kh7M5cXN',
        profileImage: "https://picsum.photos/101/101",
        vsImage: "https://picsum.photos/401/501",
        color: 'emphasis-red',
    },
    {
        id: 3,
        name: 'Ken',
        description: "Ryu's rival and friend, known for his fiery Shoryuken.",
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCL_lKTuqulZO7DiKLNCAE-6UxMHBeqjIO6QVYtBLgekMvcFbUgEfvVpbGVGMrtkxRFz5YxbRR1nrvT4SiVrWf_MDbx7HjaQ0oQQpxXAFPVcNEXtlnHk_gS6FXlGxKobvuWG6aX8hvYPOGAX_wvz1cLKU3P71gMaaMZ9vaETMsCIR8P4l6hlriQIxACbpGauhGeriF5APQQz19OZ9o6DC9PwObb4zW_3tOTIH2fZ5ehZ0Xv6vuJvee-PCXsA38mDyM_-hvr1eFeUveT',
        profileImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxwjkqW0HUgXNfVna3l0nHcE6RJklc62lBGYVuJRG6ki0Qa88SQDIFBWTwB2l6c_NlahRNnuK4wTAlQwa-ZAVXDusQxpmoghmy3-6GJrEm-akoUZRjYnDSBbNDYTlzd6_uD6Gr5n6J5aPmKs-WD016AhORXNgUmFxbaq3lYrpCIyn0Z5IEOJEguKj-EkQhSuNB0ZPTRXfnm0uCZ54IcD8TcjGuRGB7kNLGHogg1C8428IpLKmE-x1XwHjNjwJGVsgT38JrDSABT4uD",
        vsImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDPNo4X_zMqePJVRmaiBtag46-y_5vdkQA0hQWXT2ogi7s6dxQHcBtaZOCVHiWWmExB1Tbz7NMhboDWFi9GoZxUcGFoMPB7mbXEbvbCjwp-TI1kECcd-dgbZUtlVMCSUoIyYqaeOmcOAtHhbHHEobUpIm4Xj3MYF8E_2bcwWwb-ExOo1l1Nm2b5_UAokqUuduJo1xtrvXCx0TcoGOsSJYrqoWlu4WeNUg-QQqitTnTZgfiCN3qAaOQZDUfQ_XJRitiXt1-2FbLkUNiW",
        color: 'emphasis-blue',
    },
    {
        id: 4,
        name: 'Guile',
        description: 'A U.S. Air Force pilot with a signature Sonic Boom.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBajS0knULyao-x4Be1PUFbfjB04vgtOGqpHgSh9i1B1R6e2vKGsrmMpMHaMwQ_JD0fSEv4pITckq3ctjwzSPFPsqn_4PJ8E8py2sbwRQp2TqNSeIcFYtsnYGrtqFU2M9nrHIcbmX1HeCKMpWw_nH0vSuOuF8H3VYaQo5aCoyuK9owkpNfaUUEL_A5dlc_nUpTA2gx8ouvarUo1czGxcvoaEWIr-EmXFecwo6s9jJcCsU1zNu-M3uSqtT8rcfvTI0ayNf5Gk6wRae85',
        profileImage: "https://picsum.photos/102/102",
        vsImage: "https://picsum.photos/402/502",
        color: 'emphasis-yellow',
    },
    {
        id: 5,
        name: 'Dhalsim',
        description: 'A yoga master with stretchy limbs and fire-breathing.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByFFPXSCrQs4TXjfWbR-sAmqMtwh7W0MNvL82Nw8xUFH73PyCwazf_4G6tWBnTeIEThWutIDtm7JWCVfF-E3I1z21Z0orQvxXNbm2aGAs0yZAAlP9sethOlHzxKulBKm77v777f8xaMu-WJfNmJJw4iYlcq1PPKQKRhyGR2biHOLzV9N4ljNXHWdc6K63VVCF0QNNkODHBoXi8sC8KC_CKomaq76fSmVhtgWePpps29C234cDifiqsMckgU5S0biHyKxBv29LahUZu',
        profileImage: "https://picsum.photos/103/103",
        vsImage: "https://picsum.photos/403/503",
        color: 'emphasis-red',
    },
    {
        id: 6,
        name: 'Blanka',
        description: 'A wild man from the Amazon with electric attacks.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHT45UF9Pb8iY11q8xPl77LGiRmuT4EvZmK2LIBppelidRvvmXpTQaix7zxjBvkPVvhRccL_8P-Vp6fKLh93QQE2HYRiBpouQ4q-0igcj7vIN0SJsJHdYFl0UXTp7-7d3wesI72keov24mjThKIrRK46-WAmfFigBI3nbYjU1qGtuUFqoKC67CjTm76E5ojPOqFXCog5c1-PHFt3qRmv3R5znv6dgl_sRRGUB_-ewjllPV7hhE34pBUrE9SiPiBPz2z7_98L_fYtKF',
        profileImage: "https://picsum.photos/104/104",
        vsImage: "https://picsum.photos/404/504",
        color: 'emphasis-blue',
    },
    {
        id: 7,
        name: 'Zangief',
        description: 'A powerful Russian wrestler with spinning piledrivers.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD629NaUjca92-1X9EmdYhQBwDC2AZ8S1Bwf46a5pHgz_S4-z1ETgYUS8L4m6UK11Ke9geFOeINwN6RBi14CWAJyned9WsMAvN4We4A6yRgTXD4PKQ-yre66-4R7xZvk86scTD0Qzjc_snIfJ8lVyydS8HuCOJvyzPKwayN7Ab89cYhlexVrBO1qm3hKZWgiVAX6eOTx1JeJQtiprN4A6kv-9LqEkL0WG4NtatuEuG0Lrm8GUDKBbnS5-4wR0_dJh47eKzIxwPz_AOP',
        profileImage: "https://picsum.photos/105/105",
        vsImage: "https://picsum.photos/405/505",
        color: 'emphasis-yellow',
    },
     {
        id: 8,
        name: 'E. Honda',
        description: 'A sumo wrestler with a powerful Hundred Hand Slap.',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByi7IrsOqEVREJYcTvKWqXrxKJQMu1LvKr6dFaR0qJWArgYdevVlmhhiOO2Wf7xTEoj7ENVoOUGYyUth_u5lbKQlV5Nnh2BI07QbMXLozaZKuVicH2cZOwZ2I_T7PEsZ2D9mqPn3PUcuHyiM8qUF4H8MHU3Dx-6VBQ7dLHiA1j-DCO4_B6DnfwhdVOrLA83FoqibYbarBKj24C-ZsaWdWz_VBVxF7bLYRhHYL__4BfP8Kyz0f7kK2wcilS1c5kOCW5E5O2zpGndabk',
        profileImage: "https://picsum.photos/106/106",
        vsImage: "https://picsum.photos/406/506",
        color: 'emphasis-red',
    },
];

export const RYU_MOVES: Move[] = [
    { name: 'Hadoken', description: 'A powerful energy blast fired from the hands.', input: 'QCF + Punch', frameData: 'Startup: 15 frames, Active: 2 frames, Recovery: 20 frames' },
    { name: 'Shoryuken', description: 'A jumping uppercut.', input: 'DP + Punch', frameData: 'Startup: 3 frames, Active: 10 frames, Recovery: 25 frames' },
    { name: 'Tatsumaki Senpukyaku', description: 'A spinning hurricane kick.', input: 'QCB + Kick', frameData: 'Startup: 12 frames, Active: 15 frames, Recovery: 18 frames' },
    { name: 'Focus Attack', description: 'Absorb one hit and unleash a counter-attack.', input: 'MP + MK', frameData: 'Varies' },
    { name: 'Denjin Hadoken', description: 'An unblockable, chargeable Hadoken.', input: 'QCFx2 + Punch', frameData: 'Varies' },
]
