// @generated by protoc-gen-es v1.10.1
// @generated from file game.proto (package game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message game.PlayerState
 */
export const PlayerState = /*@__PURE__*/ proto3.makeMessageType(
  "game.PlayerState",
  () => [
    { no: 1, name: "player_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "character", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "x", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "y", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "action", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "frame", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "health", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "super_gauge", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message game.GameState
 */
export const GameState = /*@__PURE__*/ proto3.makeMessageType(
  "game.GameState",
  () => [
    { no: 1, name: "match_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timer", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "players", kind: "message", T: PlayerState, repeated: true },
    { no: 4, name: "winner_id", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ],
);

/**
 * Request message for streaming game state
 *
 * @generated from message game.GameStateRequest
 */
export const GameStateRequest = /*@__PURE__*/ proto3.makeMessageType(
  "game.GameStateRequest",
  () => [
    { no: 1, name: "match_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "player1_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "player2_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message game.PlayerInput
 */
export const PlayerInput = /*@__PURE__*/ proto3.makeMessageType(
  "game.PlayerInput",
  () => [
    { no: 1, name: "player_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "key_action", kind: "enum", T: proto3.getEnumType(PlayerInput_KeyAction) },
    { no: 3, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "match_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from enum game.PlayerInput.KeyAction
 */
export const PlayerInput_KeyAction = /*@__PURE__*/ proto3.makeEnum(
  "game.PlayerInput.KeyAction",
  [
    {no: 0, name: "PRESS"},
    {no: 1, name: "RELEASE"},
  ],
);

