// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file game.proto (package game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GameState, GameStateRequest, PlayerInput } from "./game_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service game.GameService
 */
export const GameService = {
  typeName: "game.GameService",
  methods: {
    /**
     * Server-side streaming RPC to send game state updates
     *
     * @generated from rpc game.GameService.StreamGameState
     */
    streamGameState: {
      name: "StreamGameState",
      I: GameStateRequest,
      O: GameState,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

/**
 * New service for player control
 *
 * @generated from service game.ControllService
 */
export const ControllService = {
  typeName: "game.ControllService",
  methods: {
    /**
     * Client-side streaming RPC: Continuously send player input to the server
     *
     * @generated from rpc game.ControllService.StreamPlayerInput
     */
    streamPlayerInput: {
      name: "StreamPlayerInput",
      I: PlayerInput,
      O: Empty,
      kind: MethodKind.ClientStreaming,
    },
  }
} as const;

