// @generated by protoc-gen-connect-es v0.13.0
// @generated from file game.proto (package game, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GameState, GameStateRequest, PlayerInput } from "./game_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service game.GameService
 */
export declare const GameService: {
  readonly typeName: "game.GameService",
  readonly methods: {
    /**
     * Server-side streaming RPC to send game state updates
     *
     * @generated from rpc game.GameService.StreamGameState
     */
    readonly streamGameState: {
      readonly name: "StreamGameState",
      readonly I: typeof GameStateRequest,
      readonly O: typeof GameState,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

/**
 * New service for player control
 *
 * @generated from service game.ControllService
 */
export declare const ControllService: {
  readonly typeName: "game.ControllService",
  readonly methods: {
    /**
     * Client-side streaming RPC: Continuously send player input to the server
     *
     * @generated from rpc game.ControllService.StreamPlayerInput
     */
    readonly streamPlayerInput: {
      readonly name: "StreamPlayerInput",
      readonly I: typeof PlayerInput,
      readonly O: typeof Empty,
      readonly kind: MethodKind.ClientStreaming,
    },
  }
};

