// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file training.proto (package training, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { TrainingMetrics, TrainingMetricsRequest } from "./training_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service training.TrainingService
 */
export const TrainingService = {
  typeName: "training.TrainingService",
  methods: {
    /**
     * Server-side streaming RPC to send training metrics updates
     *
     * @generated from rpc training.TrainingService.StreamTrainingMetrics
     */
    streamTrainingMetrics: {
      name: "StreamTrainingMetrics",
      I: TrainingMetricsRequest,
      O: TrainingMetrics,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

