// @generated by protoc-gen-es v1.10.1
// @generated from file training.proto (package training, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message training.TrainingMetrics
 */
export const TrainingMetrics = /*@__PURE__*/ proto3.makeMessageType(
  "training.TrainingMetrics",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "step", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "episode", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "loss", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 5, name: "reward", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 6, name: "q_value", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 7, name: "episode_length", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * Request message for streaming training metrics
 *
 * @generated from message training.TrainingMetricsRequest
 */
export const TrainingMetricsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "training.TrainingMetricsRequest",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

