// @generated by protoc-gen-connect-es v0.13.0
// @generated from file training.proto (package training, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { TrainingMetrics, TrainingMetricsRequest } from "./training_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service training.TrainingService
 */
export declare const TrainingService: {
  readonly typeName: "training.TrainingService",
  readonly methods: {
    /**
     * Server-side streaming RPC to send training metrics updates
     *
     * @generated from rpc training.TrainingService.StreamTrainingMetrics
     */
    readonly streamTrainingMetrics: {
      readonly name: "StreamTrainingMetrics",
      readonly I: typeof TrainingMetricsRequest,
      readonly O: typeof TrainingMetrics,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

