// @generated by protoc-gen-es v1.10.1
// @generated from file training.proto (package training, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message training.TrainingMetrics
 */
export declare class TrainingMetrics extends Message<TrainingMetrics> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: int32 step = 2;
   */
  step: number;

  /**
   * @generated from field: int32 episode = 3;
   */
  episode: number;

  /**
   * @generated from field: float loss = 4;
   */
  loss: number;

  /**
   * @generated from field: float reward = 5;
   */
  reward: number;

  /**
   * @generated from field: optional float q_value = 6;
   */
  qValue?: number;

  /**
   * @generated from field: int32 episode_length = 7;
   */
  episodeLength: number;

  constructor(data?: PartialMessage<TrainingMetrics>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "training.TrainingMetrics";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrainingMetrics;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrainingMetrics;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrainingMetrics;

  static equals(a: TrainingMetrics | PlainMessage<TrainingMetrics> | undefined, b: TrainingMetrics | PlainMessage<TrainingMetrics> | undefined): boolean;
}

/**
 * Request message for streaming training metrics
 *
 * @generated from message training.TrainingMetricsRequest
 */
export declare class TrainingMetricsRequest extends Message<TrainingMetricsRequest> {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  constructor(data?: PartialMessage<TrainingMetricsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "training.TrainingMetricsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrainingMetricsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrainingMetricsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrainingMetricsRequest;

  static equals(a: TrainingMetricsRequest | PlainMessage<TrainingMetricsRequest> | undefined, b: TrainingMetricsRequest | PlainMessage<TrainingMetricsRequest> | undefined): boolean;
}

