# src/utils/event_types.py

# Core Game Events
GAME_STATE_EVENT = "GAME_STATE"
ACTION_EVENT = "ACTION"
REWARD_EVENT = "REWARD"
EPISODE_END_EVENT = "EPISODE_END"

# Phase 7 Specific Events
RHYTHM_METRIC_EVENT = "RHYTHM_METRIC"
HUMAN_ERROR_INJECTED_EVENT = "HUMAN_ERROR_INJECTED"
NETWORK_CONDITION_EVENT = "NETWORK_CONDITION" # To log latency/loss for each packet
XAI_EVIDENCE_LINK_EVENT = "XAI_EVIDENCE_LINK"
