# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import training_pb2 as training__pb2


class TrainingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTrainingMetrics = channel.unary_stream(
                '/training.TrainingService/StreamTrainingMetrics',
                request_serializer=training__pb2.TrainingMetricsRequest.SerializeToString,
                response_deserializer=training__pb2.TrainingMetrics.FromString,
                )


class TrainingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTrainingMetrics(self, request, context):
        """Server-side streaming RPC to send training metrics updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTrainingMetrics': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrainingMetrics,
                    request_deserializer=training__pb2.TrainingMetricsRequest.FromString,
                    response_serializer=training__pb2.TrainingMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'training.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTrainingMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/training.TrainingService/StreamTrainingMetrics',
            training__pb2.TrainingMetricsRequest.SerializeToString,
            training__pb2.TrainingMetrics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
